### ISSUE TITLE
Perpetual v2 Issues

### ISSUE THREAD

**Issue by gemlabsdev** [Ming119/bingX-connector-python#10]
Hi, I am currently trying to set up a controller with the Perpetual API but the POST routes are always returning errors. All other routes seem to work fine. Could you test in your end?

**Comment by gemlabsdev** [comment]
### I think I found the solution, the url for the API as it is coded in the package is different than the current one being used by BingX. Every endpoint need to be updated. I will create a fork for this

**Comment by Ming119** [comment]
HI @gemlabsdev, sorry for not seeing your issue as you closed this issue.
you are correct, I have just done some tests on what you found to confirm the problem, and I have already updated the package.
Please run `pip install -U bingX-connector` to update the package, so you don't need to overwrite the headers.
Thank you for your contribution <3

**Comment by gemlabsdev** [comment]
Thank you for addressing this @Ming119. Very thankful that you took the time to put this library together :)
